#!/bin/sh
for imethod in bilin polin2 linpol fd sph fdy spcher; do
echo $imethod
./adv << EOF > adv.log 2>&1
39
80
21600
4
.true.
${imethod}
3
.false.
EOF
mv history.dat history_L2500km_${imethod}.dat
done

