#!/bin/sh
./adv << EOF > adv.log 2>&1
&planet /
&grid nlon=120  nlat=60 ntrunc=39 phi0="ghill " wind="sbody "/
&time nstep=80 hstep=4 deltat=21600 etf=0.00d0
 model="slag  " imethod="sph   " imethoduv="bilin "/
&semilag spectral=T fmono=F conserve=T/
&interpolate n=3/
EOF
